services:
  flibusta:
    build: .
    container_name: flibusta
    networks:
      - flibusta_net
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      proxy:
        condition: service_healthy
  proxy:
    image: v2fly/v2fly-core:latest
    container_name: v2ray
    volumes:
      - ./v2ray.json:/etc/v2ray/config.json
    command: run -c /etc/v2ray/config.json
    ports:
      - "10808:10808"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- --proxy=on --proxy=socks5://localhost:10808 http://ifconfig.me || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      - flibusta_net
  postgres:
    image: postgres:15
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - flibusta_net
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - postgres_data:/var/lib/postgresql/data  # save data from container
networks:
  flibusta_net:
    driver: bridge
volumes:
  postgres_data: